logging:
  experiment_name: gat_lstm_trial
model:
  input_size: 13
  output_size: 1
  num_lstm_layers: 2
  hidden_channels: 32
  dropout: 0.0
training:
  batch_size: 64
  num_epochs: 2
  learning_rate: 0.0001
  weight_decay: 0.0
data:
  time_steps: 100
  prediction_window: 10
  k_fold: 1

