logging:
  experiment_name: gat-gru_test
  notes: Experiment with GAT-GRU model on Dst prediction
model:
  input_size: 13
  output_size: 1
  num_gru_layers: 2
  hidden_channels: 96
  dropout: 0.0
training:
  batch_size: 64
  num_epochs: 10
  learning_rate: 0.0001
  weight_decay: 0.0
  augumentation_rate: 0.0
data:
  time_steps: 100
  prediction_window: 10
  k_fold: 1

