data:
  k_fold: 1
  prediction_window: 10
  time_steps: 100
logging:
  experiment_name: gru_2_2_1
  notes: Experiment from batch 2
model:
  dropout: 0.0
  hidden_channels: 16
  input_size: 13
  num_gru_layers: 2
  output_size: 1
training:
  augumentation_rate: 0.0
  batch_size: 32
  learning_rate: 3.0e-05
  num_epochs: 100
  weight_decay: 0.0001
