logging:
  experiment_name: gru_1_1_1
  notes: Experiment from batch 1
model:
  input_size: 13
  output_size: 1
  num_gru_layers: 2
  hidden_channels: 16
  dropout: 0.0
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  augumentation_rate: 0.0
data:
  time_steps: 100
  prediction_window: 10
  k_fold: 1

